name: pythonexpenseapp
description: "Budget App - Track and analyze your expenses with CSV import and category breakdown."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  path_provider: ^2.1.0
  uuid: ^4.0.0
  csv: ^6.0.0
  share_plus: ^7.2.0
  provider: ^6.1.0
  file_picker: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
